apiVersion: v1
kind: ConfigMap
metadata:
  name: komiser
data:
  credentials: |-
    [default]
    region = "us-east-1"
    role_arn = "{{ .Values.aws.arn}}"
    web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"

    [sqlite]
    file="komiser.db"